meal_plans/urls.py
from django.urls import path


from meal_plans.views import (
    MealPlansCreateView,
    MealPlansUpdateView,
    MealPlansDetailView,
    MealPlansListView,
    MealPlansDeleteView,
)

urlpatterns = [
    path("", MealPlansListView.as_view(), name="meal_plans_list"),
    path("create/", MealPlansCreateView.as_view(), name="meal_plans_create"),
    path("<int:pk>/", MealPlansDetailView.as_view(), name="meal_plans_detail"),
    path(
        "<int:pk>/edit/", MealPlansUpdateView.as_view(), name="meal_plans_edit"
    ),
    path(
        "<int:pk>/delete/",
        MealPlansDeleteView.as_view(),
        name="meal_plans_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import show_tags

urlpatterns = [
    path("", show_tags, name="tags_list"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

# from django.core.validators import MaxValueValidator, MinValueValidator


AUTH_USER_MODEL = settings.AUTH_USER_MODEL


class MealPlans(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateTimeField()
    owner = models.ForeignKey(
        AUTH_USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")


#     description = models.TextField()
#     image = models.URLField(null=True, blank=True)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.name


# class Measure(models.Model):
#     name = models.CharField(max_length=30, unique=True)
#     abbreviation = models.CharField(max_length=10, unique=True)

#     def __str__(self):
#         return self.name


# class FoodItem(models.Model):
#     name = models.CharField(max_length=100, unique=True)

#     def __str__(self):
#         return self.name


# class Ingredient(models.Model):
#     amount = models.FloatField(validators=[MaxValueValidator(20)])
#     recipe = models.ForeignKey(
#         "Meal Plan",
#         related_name="ingredients",
#         on_delete=models.CASCADE,
#     )
#     measure = models.ForeignKey("Measure", on_delete=models.PROTECT)
#     food = models.ForeignKey("FoodItem", on_delete=models.PROTECT)

#     def __str__(self):
#         amount = str(self.amount)
#         measure = self.measure.name
#         food = self.food.name
#         return amount + " " + measure + " " + food


# class Step(models.Model):
#     recipe = models.ForeignKey(
#         "Meal Plan",
#         related_name="steps",
#         on_delete=models.CASCADE,
#     )
#     order = models.PositiveSmallIntegerField()
#     directions = models.CharField(max_length=300)
#     food_items = models.ManyToManyField("FoodItem", blank=True)

#     def __str__(self):
#         return str(self.order) + ". " + self.directions


# class Rating(models.Model):
#     value = models.PositiveSmallIntegerField(
#         validators=[
#             MaxValueValidator(5),
#             MinValueValidator(1),
#         ]
#     )
#     recipe = models.ForeignKey(
#         "Meal Plan",
#         related_name="ratings",
#         on_delete=models.CASCADE,
#     )

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from meal_plans.models import MealPlans
from django.contrib.auth.mixins import LoginRequiredMixin
from recipes.models import Recipe


class MealPlansListView(LoginRequiredMixin, ListView):
    model = MealPlans
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        querystring = self.request.GET.get("q")
        if querystring is None:
            querystring = ""
        print(self.queryset)
        return MealPlans.objects.filter(owner=self.request.user)


class MealPlansCreateView(LoginRequiredMixin, CreateView):
    model = MealPlans
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def create_meal_plans(self, request):
        if request.method == "POST":
            form = MealPlans(request.POST)
            if form.is_valid():
                plan = form.save(commit=False)
                plan.owner = self.request.user
                plan.save()
                form.save_m2m()
                return redirect("meal_plans_detail", pk=plan.id)


class MealPlansDetailView(DetailView):
    model = MealPlans
    template_name = "meal_plans/detail.html"
    context_object_name = "mealplan"


class MealPlansUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlans
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_list")


class MealPlansDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlans
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="delete-form">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ mealplans }}"?</p>
      {{ form.as_p }}
      <div>
        <button class="button">Delete</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
<main class="mealplans-detail">
  <div>
    <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
    <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
  </div>
  {% if mealplan.image %}
  <img src="{{ mealplan.image }}" class="pull-right">
  {% endif %}
  <h1>{{ mealplan.name }}</h1>

  <p>served on {{ mealplan.date }}</p>
  {% for recipe in mealplan.recipes.all %}
  <a href="{% url 'recipe_detail' recipe.id %}">{{recipe.name }}</a>

  {% endfor %}

  {% endblock %}






  <!-- <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in mealplans.ingredients.all %}
      <tr>
        <td>{{ ingredient.amount }}</td>
        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in mealplans.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main> -->

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="mealplans-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}

{% block content %}
<main class="mealplans-grid">
  {% for meal_plan in mealplans_list %}
  <div class="mealplans-card">
    <h2 class="mealplans-card-title">
      <a href="{% url 'meal_plans_detail' meal_plan.pk %}">{{ meal_plan.name }}</a>
    </h2>
    <p class="mealplans-card-date">{{ meal_plan.updated }}</p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}